SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE Game;
DROP TABLE Event;
DROP TABLE Player;
DROP TABLE Event_staff;
DROP TABLE Hosts;
DROP TABLE Competes_in;
DROP TABLE Tournament_organizers;
DROP TABLE Helpers;
DROP TABLE Stream_operators;
DROP TABLE Controllers;
DROP TABLE Main_characters;
